### ISSUE TITLE
[Query]: does helpersConvertInputToList.py always need to UnwrapElement ?

### ISSUE THREAD

**Issue by adambear82** [Amoursol/dynamoPython#2]
Thanks for starting this resource, looks really useful :)

https://github.com/Amoursol/dynamoPython/blob/05bbfb925fcc86b6a07ec0d95106239c2390e798/helpers/helpersConvertInputToList.py#L22-L25

I was wondering why you used `UnwrapElement` is that always necessary?
or do you include it just in case its necessary?
sometimes I use this single line that I picked up from looking at packages

`if not isinstance(inputs, list): inputs = [inputs]`

which is pretty similar but skips over doing anything that is already a list so there wouldn't be the opportunity to `UnwrapElement` for objects that are already in a list

**Comment by Amoursol** [comment]
Hello Adam,

The single line item you use is perfectly acceptable - the reality is that there are many ways to achieve results in Python. I’ll be adding in a couple of other versions to showcase just such comparatively to [Johns version](https://github.com/Amoursol/dynamoPython/blob/master/helpers/helpersConvertInputToList.py) embedded in your query above. 

Typically, the only reason you need to UnwrapElement is if you want access to the ```underlying Revit API calls``` themselves (And bare in mind you’ll have to wrap them up again if so for the Dynamo context to understand them).

**Comment by adambear82** [comment]
thanks sol thats interesting

![image](https://user-images.githubusercontent.com/32963786/42892938-f198aac4-8aaa-11e8-8c15-eefaedea275a.png)

```
wrapped = dir(IN[0])
unwrapped = dir(UnwrapElement(IN[0]))

wrappedonly = []
unwrappedonly = []
unandwrapped = []
lens = []

for i in wrapped :
	if i not in unwrapped :
		wrappedonly.append(i)

for i in unwrapped :
	if i not in wrapped :
		unwrappedonly.append(i)

for i in unwrapped :
	if i in wrapped :
		unandwrapped.append(i)

wraps = wrapped, wrappedonly, unandwrapped, unwrappedonly, unwrapped
for i in wraps : lens.append(len(i))
nam = 'wrapped', 'wrapped only', 'unwrapped and wrapped', 'unwrapped only', 'unwrapped'
ven = [ [x, y] for x,y in zip(lens, nam) ]

OUT = ven, [ [x, y] for x,y in zip(ven, wraps) ]
```

**Comment by Amoursol** [comment]
This information has been moved to the Wiki.
