### ISSUE TITLE
[Query]: would you add extra detail to filteredElementCollectorByParameter.py for additional rules and evaluators or see those as separate ?

### ISSUE THREAD

**Issue by adambear82** [Amoursol/dynamoPython#3]
for example
https://github.com/Amoursol/dynamoPython/blob/1c8fc5ab393c75d158682421bee4d6d614c64cd4/revitAPI/filteredElementCollectorByParameter.py#L27-L30

an evaluator for greater than
`evaluator = FilterNumericGreater()`
which you could also use `not` for less than

an evaluator for string contains
`evaluator = FilterStringContains()`

an evaluator for strings equals
`evaluator = FilterStringEquals()`

a rule for strings
`rule = FilterStringRule(provider, evaluator, test, False)`

a rule for doubles
`rule = FilterDoubleRule(provider, evaluator, test, 10**-3)`

a rule for element ids
`rule = FilterElementIdRule(provider, evaluator, test)`

might also be helpful to refer to [revitapidocs.com](http://www.revitapidocs.com/2018.1/fb011c91-be7e-f737-28c7-3f1e1917a0e0.htm) when trying to figure out what the param is
https://github.com/Amoursol/dynamoPython/blob/1c8fc5ab393c75d158682421bee4d6d614c64cd4/revitAPI/filteredElementCollectorByParameter.py#L22-L23

**Comment by Amoursol** [comment]
This particular example is supposed to be able to be 'ran' simply through a copy and paste into a Python node. I'm torn as to the format for your suggestion and welcome any thoughts.

**Comment by adambear82** [comment]
I wondered if you might add some more `#comments` which show a few options, or alternatively you could create lots of different *.py files for different combinations of filters, rules, evaluators

for my own purposes I didn't like having lots of separate files as there could be a lot of combinations of filters, rules, evaluators, so I wrote an example that did all sorts of things but with lots of commenting out

```
'''
exploration of the filtered element collector (fec)

http://thebuildingcoder.typepad.com/blog/2010/06/parameter-filter.html
https://forum.dynamobim.com/t/python-custom-rules-for-filteredelementcollector/21135/2?u=adam_bear1
http://www.revitapidocs.com/2018.1/fb011c91-be7e-f737-28c7-3f1e1917a0e0.htm

'''

#------------------------------------------
#boilerplate
#------------------------------------------

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference('RevitServices')
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
fec = FilteredElementCollector(doc)

#------------------------------------------
#useful list of bip to copy paste from revitapidocs.com
#------------------------------------------

#StringValues
'ALL_MODEL_DESCRIPTION'
'ALL_MODEL_MARK'
'ALL_MODEL_INSTANCE_COMMENTS'
'ALL_MODEL_TYPE_COMMENTS'

#ElementId
'ID_PARAM'

#Integers
'WALL_BOTTOM_IS_ATTACHED'
'WALL_TOP_IS_ATTACHED'
'WALL_ATTR_ROOM_BOUNDING'
'RELATED_TO_MASS'
'WALL_STRUCTURAL_SIGNIFICANT'
'STRUCTURAL_ANALYTICAL_MODEL'

#Doubles
'ALL_MODEL_COST'

enum = 'WALL_STRUCTURAL_SIGNIFICANT'

#------------------------------------------
#define myclass, bip, provider
#------------------------------------------

myclass = Wall
#bip = BuiltInParameter.WALL_STRUCTURAL_SIGNIFICANT
bip = eval('BuiltInParameter.' + enum)
provider = ParameterValueProvider(ElementId(bip))

#------------------------------------------
#evaluate strings, elem id, integer, doubles
#------------------------------------------

#evaluate string values
#test = 'aaa'
#evaluator = FilterStringContains()
#evaluator = FilterStringEquals()
#rule = FilterStringRule(provider, evaluator, test, False)

#evaluate element id
#evaluator = FilterNumericEquals()
#evaluator = FilterNumericGreater()
#test = ElementId(0)
#rule = FilterElementIdRule(provider, evaluator, test)

#evaluate integer values
test = 1
evaluator = FilterNumericEquals()
#evaluator = FilterNumericGreater()
rule = FilterIntegerRule(provider, evaluator, test)

#evaluate double values
#test = 5.55
#evaluator = FilterNumericEquals()
#evaluator = FilterNumericGreater()
#rule = FilterDoubleRule(provider, evaluator, test, 10**-3)

#------------------------------------------
#fec of class passing filter to elements
#------------------------------------------

filter = ElementParameterFilter(rule)
elems = fec.OfClass(myclass).WherePasses(filter).ToElements()

#------------------------------------------
#output
#------------------------------------------

OUT = elems
```

**Comment by Amoursol** [comment]
I think it useful to have my example as a 'run and done' - then another uploaded as 'mix and match' version! Feel free to create a **Pull Request** for such!
