### ISSUE TITLE
[Query:] should all scripts include a link to github ?

### ISSUE THREAD

**Issue by adambear82** [Amoursol/dynamoPython#35]
maybe it would be a good idea for all scripts to include a link to github, obviously the original user will know where it is from, but if python scripts get copy pasted and shared, might be an idea to include a link... ?

I think it might be too much to link to the raw code page just the front page for dynamo python, or maybe a wiki ?

**Comment by Amoursol** [comment]
Just to the front page sounds simpler. Agreed. Great idea :)

**Comment by adambear82** [comment]
If you add something to the contributing page I'll update my code to suit

**Comment by adambear82** [comment]
perhaps a little silly....
...all code could include something like this, which if just copy pasted wouldn't do anything, but if the function is called with the correct argument, links to git

```
def easterEgg(hunt=None) :
	if hunt == 'hunt' :
		import sys
		sys.path.append('C:\\Program Files (x86)\\IronPython 2.7\\Lib')
		import webbrowser
		webbrowser.open('https://github.com/Amoursol/dynamoPython')
easterEgg()
```

**Comment by radumg** [comment]
> If you add something to the contributing page I'll update my code to suit

have a look at the PR above now @Amoursol & @adambear82 - should be a starting point for discussion at least!
