### ISSUE TITLE
[Query]: is this a typo in listReplaceNulls.py ?

### ISSUE THREAD

**Issue by adambear82** [Amoursol/dynamoPython#4]
https://github.com/Amoursol/dynamoPython/blob/1c8fc5ab393c75d158682421bee4d6d614c64cd4/workflow/listReplaceNulls.py#L18

should be ?

`results.append(replacementItem)`

as

https://github.com/Amoursol/dynamoPython/blob/1c8fc5ab393c75d158682421bee4d6d614c64cd4/workflow/listReplaceNulls.py#L10

**Comment by Amoursol** [comment]
Hello Adam,

This is indeed a typo - thanks for the spot! I've amended it now.

If you see something similar in future - you can create a 'Pull Request' to amend it :)
