### ISSUE TITLE
[Request]  Add code line length limit to improve readiability 

### ISSUE THREAD

**Issue by pabloderen** [Amoursol/dynamoPython#6]
This is a request to add a maximum character length to the code lines to include in CONTRIBUTING.MD #5
This will improve readability on RPS and small screens. We can use 79 characters as suggested by pep-0008.

[https://www.python.org/dev/peps/pep-0008/?#maximum-line-length](https://www.python.org/dev/peps/pep-0008/?#maximum-line-length)

[EDIT] Typos

**Comment by Amoursol** [comment]
Hello Pablo,

This comment has been added to the Contributing.md.

I'll be amending my existing code to suit over the next few days.

**Comment by adambear82** [comment]
the default width of the python script editor is actually rather narrow, 74 characters at my count

![image](https://user-images.githubusercontent.com/32963786/43087367-a4faa514-8e97-11e8-95c0-c68bbb00867d.png)
